### ISSUE TITLE
Can this Lib use in arduino IDE?

### ISSUE THREAD

**Issue by Rita858** [imxieyi/esp32-lcd12864-serial#1]
I just want to find a 12864 Lib that can run on ESP32 through arduino IDE. But there is only one Lib that can run on ESP32. Thus, I wonder if it can use in arduino IDE.

**Comment by imxieyi** [comment]
There are already libraries supporting this. You can search for arduino libraries. It does not have to be designed for ESP32.

**Comment by Rita858** [comment]
> There are already libraries supporting this. You can search for arduino libraries. It does not have to be designed for ESP32.

Thanks，bro.
